"""create market_ticks hypertable-ready schema

Revision ID: 58716bcd0548
Revises: 
Create Date: 2026-08-17 06:12:59.570897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58716bcd0548'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_ticks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('broker_symbol', sa.String(length=30), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    op.create_index(op.f('ix_market_ticks_symbol'), 'market_ticks', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_ticks_timestamp'), 'market_ticks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_ticks_timestamp'), table_name='market_ticks')
    op.drop_index(op.f('ix_market_ticks_symbol'), table_name='market_ticks')
    op.drop_table('market_ticks')
    # ### end Alembic commands ###
